name: SRCCON
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
plugins:
  - jekyll-redirect-from
exclude: ['*.yml']
collections:
  transcripts:
    output: true
    permalink: /:collection/:title/
  share:
    output: true
    permalink: /:collection/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: layout
      logo: /media/img/datainstitutelogo_navy.png
      title: The Data Institute
      description: The Data Institute is a free, hands-on workshop that teaches people how to report, design, and develop interactive graphics and data-driven news applications.
